### ISSUE TITLE
Just FYI... into the future... 1. 2. 3.

### ISSUE THREAD

**Issue by xbman** [xbman/Repo#2]
Just FYI... into the future... 1. 2. 3.
*1:  Been working on a cool new horoscopes program addon... still working on it..... looking cool tho...
*2: VLive will be down soon enough.. for their flash to html5 transition is coming very soon....
...So be ready for that.... and it may take me a while to fix that indeed... we'll see soon enough.
... I will be on it I assure you.... for when it happens.... so just please stand by....
*3: I may just make a new forum soon.. for my addons.. more than likely i will...

So I am well aware of what is coming.. are you? O_O

EDIT: Horoscope Daily added....
.

**Comment by ThePiperNeverDies** [comment]
hey just wanted to say thanks for the 3.9 update 
took me a while to figure out how to post here ha...
using vlive  on kodi running straight to sony android tv
works very well..,  
well, as long as vaughn tv  does not tinker too much ..

**Comment by xbman** [comment]
Hey.. thanks for the feedback. :-)
It's kinda rigged up a bit, but it works for the moment. hehe...
.. but yep.. he likes to tinker with his site a lot indeed.

**FYI**: The html url for now is: https://xbman.github.io/
..for some reason the xbman.cu.cc domain just will not work for me on git anymore...
..dunno why. I may just make that the new forum url anyway.
And a forum will be much easier for people to reply on than on git.

**EDIT**: New forum is up: http://xbman.cu.cc

**Comment by xbman** [comment]
New forum url: http://xbman.usa.cc

**Comment by xbman** [comment]
closed.. outdated.
